name: Build Blog Metadata

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'pinned/**'
      - 'profile.md'
      - 'config.md'
      - 'scripts/build.js'
      - '.github/workflows/build-metadata.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
